Topic#29/add blueprint support
ShredEagle/entity pull request #30
Opened 2023-11-14 15:51 UTC by FranzPoize

2024-02-21 17:45 UTC, FranzPoize commented
Can you review that @Adnn ?

2024-02-22 14:22 UTC, Adnn requested changes

2024-02-22 14:22 UTC, Adnn commented on src/apps/entity_tests/Query_tests.cpp
> +        std::array<Handle<Entity>, 3> entities{
2 entities, not 3 (nitpicking)

2024-02-22 14:22 UTC, Adnn commented on src/apps/entity_tests/Query_tests.cpp
> +                const double a[] = {
Also 2

2024-02-22 14:22 UTC, Adnn commented on src/libs/entity/entity/Archetype.h
> +template<Archetype::Operation N_operation>
Is it used outside of `Archetype.cpp`. If not, it should probably be moved there.

2024-02-22 14:22 UTC, Adnn commented on src/libs/entity/entity/Entity.cpp
> +const TypeSet Handle<Entity>::getComponentsInfo() const
I would have reused the existing name `getTypeSet`, for consistency.

2024-02-22 14:22 UTC, Adnn commented on src/libs/entity/entity/EntityManager.cpp
> +#include <cassert>
`c` last ; )

2024-02-22 14:22 UTC, Adnn commented on src/libs/entity/entity/Archetype.h
> +    std::unique_ptr<Archetype> makeRestrictedFromTypeId(const ComponentId aId) const;
Is the new dynamic overload used? (or is it for client consumption?)

2024-02-22 14:22 UTC, Adnn commented on src/libs/entity/entity/detail/QueryBackend.h
> +                     GetTypeSet().begin(), GetTypeSet().end()) && std::find(aCandidateTypeSet.begin(), aCandidateTypeSet.end(), getId<Blueprint>()) == aCandidateTypeSet.end())
`\n`

2024-02-22 14:22 UTC, Adnn commented on src/libs/entity/entity/EntityManager.cpp
> +Handle<Entity> EntityManager::createFromBlueprint(Handle<Entity> aBlueprint, const char * aName)
Maybe we can extract a sort of `Entity::copy()` for the API, and use it to implement as a copy then remove.

2024-10-09 16:17 UTC, merged